version: "3.8"
services:
  db:
    image: postgres:13.0
    restart: always
    volumes:
      - ./log/postgresql:/var/log/postgresql
    ports:
      - '5432:5432'  # This is just for pgAdmin access
    environment:
      POSTGRES_PASSWORD: secret
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5000:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
